apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cheese
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: carlosstilton.cdanmar.com
    http:
      paths:
      - path: /
        backend:
          serviceName: stilton
          servicePort: http
  - host: carloscheddar.cdanmar.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cheddar
          servicePort: http
  - host: carloswensleydale.cdanmar.com
    http:
      paths:
      - path: /
        backend:
          serviceName: wensleydale
          servicePort: http
  - host: carloswensleydale.cdanmar.com
    http:
      paths:
      - path: /
        backend:
          serviceName: wensleydale
          servicePort: http