apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cheese
  namespace: cheese
  annotations:
    certmanager.k8s.io/acme-challenge-type: http01
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - stilton.barnprojects.com
    secretName: stilton-tls-tdwnk
  - hosts:
    - cheddar.barnprojects.com
    secretName: cheddar-tls-d2zbg 
  - hosts:
    - wensleydale.barnprojects.com
    secretName: wensleydale-tls-7tfkz
  rules:
  - host: stilton.barnprojects.com
    http:
      paths:
      - path: /
        backend:
          serviceName: stilton
          servicePort: http
  - host: cheddar.barnprojects.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cheddar
          servicePort: http
  - host: wensleydale.barnprojects.com
    http:
      paths:
      - path: /
        backend:
          serviceName: wensleydale
          servicePort: http
